(define (assembunny program)
  (define ip 0)
  (define status 'ok)
  (define memory (make-fxvector 5 0))
  (define N (length program))
  (define (symbol->register r)
    ;; (- 5 (length (memq r '(a b c d e))))
    (case r ((a) 0) ((b) 1) ((c) 2) ((d) 3) ((e) 4)))
  (define (val x)
    (if (integer? x) x
	(fxvector-ref memory (symbol->register x))))
  (define (step)
    (if (not (<= 0 ip (fx1- N)))
	(set! status 'done)
	(match (list-ref program ip)
	  (('cpy x y)
	   (fxvector-set! memory (symbol->register y) (val x))
	   (inc! ip))
	  (('inc x)
	   (fxvector-modify! memory (symbol->register x) fx1+)
	   (inc! ip))
	  (('dec x)
	   (fxvector-modify! memory (symbol->register x) fx1-)
	   (inc! ip))
	  (('jnz x y)
	   (if (fxzero? (val x))
	       (inc! ip)
	       (inc! ip (val y)))))))
  (define (set-register! x v)
    (fxvector-set! memory (symbol->register x) v))
  (define (get-register x)
    (fxvector-ref memory (symbol->register x)))
  (lambda (me . args)
    (case me
      ((step) (step))
      ((status) status)
      ((ip) ip)
      ((memory) memory)
      ((set-register!) (apply set-register! args))
      ((get-register) (apply get-register args)))))

(define (step machine)
  (machine 'step))

(define (memory machine)
  (machine 'memory))

(define (status machine)
  (machine 'status))

(define (set-register! machine register value)
  (machine 'set-register! register value))

(define (get-register machine register)
  (machine 'get-register register))

(define (run-until-halt machine)
  (let lp ()
    (unless (eq? 'done (status machine))
      (step machine)
      (lp))))
