(load "~/code/aoc/load.ss")
(advent-year 24) (advent-day 06)
(define in (parse-advent lines-raw))
(define N (length in))
(define G (make-eqv-hashtable))
(define z0)
;; populate grid G and find starting position
(do ((x 0 (1+ x)))
    ((= x N) (values z0 G))
  (do ((y 0 (1+ y)))
      ((= y N))
    (match (string-ref (list-ref in y) x)
      (#\# (hashtable-set! G (+ y (* 0+i x)) #t))
      (#\^ (set! z0 (+ y (* 0+i x))))
      (_ (void)))))

(define (run z0 dz0 G)
  (define S (make-eqv-hashtable))
  (define T (make-hashtable equal-hash equal?))
  (let step ((z z0) (dz dz0) (i 0))
    (hashtable-set! T (cons z dz) #t)
    (hashtable-set! S z #t)
    (let ((u (+ z dz)))
      (cond ((or (< (real-part u) 0)
		 (= (real-part u) N)
		 (< (imag-part u) 0)
		 (= (imag-part u) N))
	     S)
	    ((hashtable-ref T (cons u dz) #f) 'cycle-detected)
	    ((hashtable-ref G u #f) (step z (* dz 0-i) (1+ i)))
	    (else (step u dz (1+ i)))))))

(define (part-a)
  (vector-length (hashtable-keys (run z0 -1 G))))

(define (part-b)
  (define count 0)
  ;; only need to check adding walls to squares on original path
  (vector-for-each (lambda (z)
		     (let ((H (eqv-hashtable-copy G))
			   (dz (if (eqv? (- z 1) z0) 0+i -1)))
		       (unless (hashtable-ref H z #f)
			 (hashtable-set! H z #t)
			 (when (eq? 'cycle-detected (run z0 dz H))
			   (inc! count)))))
		   (hashtable-keys (run z0 -1 G)))
  count)
