(load "~/code/aoc/load.ss")
(advent-year 19)
(advent-day 15)

(define program
  (parse-advent comma-separated))

(define north 1)
(define south 2)
(define east 4)
(define west 3)
(define wall 0)
(define moved 1)
(define oxygen-system 2)

(define (dir->instr z)
  (match z
    (1 east)
    (-1 west)
    (0+i north)
    (0-i south)))

(define g (make-eqv-hashtable))
(define m (intcode program))
(define *tank*)

(define (random-element lst)
  (list-ref lst (random (length lst))))

(define (random-walk)
  (define loc 0)
  (define m (intcode program))
  (define j 0)
  (define frontier (make-eqv-hashtable))
  (define (next loc)
    (define old '())
    (define new '())
    (for-all (lambda (z)
               (hashtable-delete! frontier z)
               (match (hashtable-ref g z 'idk)
                 ('idk (push! z new))
                 ('wall (void))
                 ('open (push! z old))
                 ('tank (push! z old))))
             (grid4 loc))
    (for-all (lambda (z)
               (hashtable-set! frontier z loc))
             new)
    (if (pair? new)
        (random-element new)
        (random-element old)))
  (let walk ()
    (inc! j)
    (let ((loc* (next loc)))
      (m 'in (dir->instr (- loc* loc)))
      (run-until-halt m)
      (match (read-output m)
        ((0) (hashtable-set! g loc* 'wall))
        ((1) (hashtable-set! g loc* 'open) (set! loc loc*))
        ((2) (hashtable-set! g loc* 'tank) (set! loc loc*) (set! *tank* loc)))
      (when (zero? (hashtable-size frontier))
        (showme loc)
        (format #t "iteration: ~a~%frontier-size: ~a~%" j (hashtable-size frontier)))
      (unless (zero? (hashtable-size frontier))
        (when (zero? (mod j 10000))
          (showme loc)
          (format #t "iteration: ~a~%frontier-size: ~a~%" j (hashtable-size frontier)))
        (walk)))))

(define (partA)
  (bfs-distance 0 *tank* map-adjacent))

(define (partB)
  (apply max (vector->list
              (hashtable-values
               (bfs-result-distances (bfs *tank* map-adjacent))))))

(define (solve)
  ;; seeds, 6 fast 7 slow. 13 nice, 16
  (random-walk)
  (display-ln (list (partA) (partB))))

(define (map-adjacent z)
  (filter (lambda (z)
            (memq (hashtable-ref g z 'idk) '(open tank)))
          (grid4 z)))

(define (showme loc)
  (define-values (xlo xhi ylo yhi)
    (bounding-box-C (vector->list (hashtable-keys g))))
  (do ((i (1- xlo) (1+ i)))
      ((> i (1+ xhi)))
    (do ((j (1- ylo) (1+ j)))
        ((> j (1+ yhi)) (newline))
      (let ((z (make-rectangular i j)))
        (cond ((eqv? z loc)
               (display-with-foreground 'red #\@))
              (else
               (match (hashtable-ref g (make-rectangular i j) 'idk)
                 ('idk (display-with-foreground 'blue #\?))
                 ('wall (display-with-foreground 'green #\#))
                 ('open (display #\space))
                 ('tank (display-with-foreground 'red #\O)))))))))
